apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandkube-deployment
  namespace: sandkube-ns
spec:
  selector:
    matchLabels:
      app: sandkube
  replicas: 2
  template:
    metadata:
      labels:
        app: sandkube
    spec:
      containers:
      - name: sandkube
        imagePullPolicy: Never
        image: sandkube
        ports:
        - containerPort: 3000