apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandkube-deployment
  namespace: sandkube-ns
spec:
  selector:
    matchLabels:
      app: sandkube
  replicas: 4
  template:
    metadata:
      labels:
        app: sandkube
    spec:
      containers:
      - name: sandkube
        image: ccheadle/hello-go:latest
        ports:
        - containerPort: 8080