apiVersion: v1
kind: Service
metadata:
  name: sandkube-service
  namespace: sandkube-ns
  labels:
    app: sandkube
spec:
  type: LoadBalancer
  selector:
    app: sandkube
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080